### ISSUE TITLE
wrong remote path

### ISSUE THREAD

**Issue by rgiordani** [nikvdp/pbproxy#1]
I didn't try it yet, but how can `ssh "$remote_host" '~/bin/pbcopy'` work if the pbcopy path is `~/.pbproxy`?

**Comment by nikvdp** [comment]
You are absolutely right, it wouldn't have! Thanks for the catch. That path works on my machines because that's where I keep them, that path was from my local rc files (which this was recently extracted from)

Fixed in https://github.com/nikvdp/pbproxy/commit/878b470c707d8e90ff7951b25f616ff47b7fa9db
